name: arm
on: [push, pull_request]

jobs:
  test:
    name: dub
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies on Ubuntu
        run: sudo apt-get update && sudo apt-get install libev-dev libevent-dev libsqlite3-dev gcc clang -y

      - name: Install LDC and DUB
        run: sudo apt-get install ldc gdc-12 dub -y

      - name: Show versions
        run: |
          dub --version
          ldc2 --version

      - name: Run tests
        run: |
          dub test --compiler=ldc2
          DFLAGS="-unittest -O -g" dub test --compiler=ldc2

      - name: Run benchmarks
        run: |
          echo "== GCC ==" && gcc -O3 -g benchmark.c && time ./a.out
          echo "== Clang ==" && clang -O3 -g benchmark.c && time ./a.out
          echo "== GDC 12 (std.int128) ==" && gdc-12 -O3 -frelease -fno-weak-templates -g benchmark.d && time ./a.out
          sed -i s/std.int128/speedy.int128/ benchmark.d
          ldc2 -O -g -release benchmark.d speedy/int128.d speedy/int128_ldc.d speedy/int128_ldc_32bit_fallback.d
          echo "== LDC (speedy.int128) ==" && time ./benchmark
