name: x86-bench
on: [push, pull_request]

jobs:
  test:
    name: benchmark
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Install 32-bit support on Ubuntu
        run: sudo apt-get update && sudo apt-get install gcc-multilib -y

      - name: Run benchmark for GCC
        run: |
          gcc -O3 -g benchmark.c
          time ./a.out && time ./a.out

      - name: Run benchmark for Clang
        run: |
          clang -O3 -g benchmark.c
          time ./a.out && time ./a.out

      - name: Install LDC 1.30.0
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-1.30.0

      - name: Run benchmark for 32-bit LDC 1.30.0 (speedy.int128)
        run: |
          dub build --single --build release --config=speedy --force -a x86 benchmark.d
          time ./benchmark && time ./benchmark

      - name: Run benchmark for 32-bit LDC 1.30.0 (std.int128)
        run: |
          dub build --single --build release --config=std --force -a x86 benchmark.d
          time ./benchmark && time ./benchmark

      - name: Run benchmark for 64-bit LDC 1.30.0 (speedy.int128)
        run: |
          dub build --single --build release --config=speedy --force -a x86_64 benchmark.d
          time ./benchmark && time ./benchmark

      - name: Run benchmark for 64-bit LDC 1.30.0 (std.int128)
        run: |
          dub build --single --build release --config=std --force -a x86_64 benchmark.d
          time ./benchmark && time ./benchmark

      - name: Install DMD 2.100.2
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-2.100.2

      - name: Run benchmark for 32-bit DMD 2.100.2 (speedy.int128)
        run: |
          dub build --single --build release --config=speedy --force -a x86 benchmark.d
          time ./benchmark && time ./benchmark

      - name: Run benchmark for 32-bit DMD 2.100.2 (std.int128)
        run: |
          dub build --single --build release --config=std --force -a x86 benchmark.d
          time ./benchmark && time ./benchmark

      - name: Run benchmark for 64-bit DMD 2.100.2 (speedy.int128)
        run: |
          dub build --single --build release --config=speedy --force -a x86_64 benchmark.d
          time ./benchmark && time ./benchmark

      - name: Run benchmark for 64-bit DMD 2.100.2 (std.int128)
        run: |
          dub build --single --build release --config=std --force -a x86_64 benchmark.d
          time ./benchmark && time ./benchmark

      - name: Install GDC 9/12 and DUB from the Ubuntu reposotory
        run: sudo apt-get install gdc-9 gdc-12 dub -y

      - name: Show versions
        run: |
          dub --version
          gdc-9 --version
          gdc-12 --version
          gcc --version
          clang --version

      - name: Run benchmark for GDC 9 (speedy.int128)
        run: |
          dub build --single --build release --config=speedy --compiler=gdc-9 --force benchmark.d
          time ./benchmark && time ./benchmark

      - name: Run benchmark for GDC 12 (std.int128)
        run: |
          dub build --single --build release --config=std --compiler=gdc-12 --force benchmark.d
          time ./benchmark && time ./benchmark

      - name: Run benchmark for GDC 12 (speedy.int128)
        run: |
          dub build --single --build release --config=speedy --compiler=gdc-12 --force benchmark.d
          time ./benchmark && time ./benchmark
